### ISSUE TITLE
Add support for multiple entrypoints

### ISSUE THREAD

**Issue by tatarianBarbarian** [evilmartians/astro-typedoc#25]
Now, the code works with a single entry point.

It's possible for code to have multiple of them, and we should check how to handle it the right way.
We may want to split navigation to avoid possible confusion, for example.

This task is for checking what can go wrong and fixing it.

- [x] Adapt navigation - https://github.com/evilmartians/astro-typedoc/pull/36
- [ ] Make sure cross-module/cross-project links work - https://github.com/evilmartians/astro-typedoc/pull/37
- [ ] Fix folder names for Astro to make pages work - https://github.com/evilmartians/astro-typedoc/pull/38

**Comment by tatarianBarbarian** [comment]
Navigation object should be changed if we want to use it with multiple entry points.

We will add a new field to the navigation object, `type`, which can be `flat | modular`.

For flat navigation there will be following structure:

```js
{
  type: 'flat',
  items: [
    { title: '...', url: '...' }
  ]
}
```

For modular navigation structure will be following:

```js
{
  type: 'modular',
  modules: [
    {
      moduleName: 'module1',
      items: [{ title: '...', url: '...' }]
    },
    {
      moduleName: 'module2',
      items: [{ title: '...', url: '...' }]
    }
  ]
}
```

**Comment by ai** [comment]
I hope in `Sidebar` component we will be able to make this navigation flat.

For Logux we need to mix all components, but for Nano Stores it will be better to keep them separately.
